config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  get '', to: 'maps#show', constraints: lambda { |r| r.subdomain.present? && r.subdomain != 'www' }
  root 'maps#index'

  require 'sidekiq/web'
  authenticate :user, lambda { |u| u.id == 1 } do
    mount Sidekiq::Web => '/sidekiq'
  end

  arrayMap = (1..6).map { |x| %Q(get 'index#{x}'\n)}
  arrayMapReduce = arrayMap.reduce { |x,y| x+y }

  resources :welcome do
    collection do
      get 'demo'
      get 'search_location'
      eval(arrayMapReduce)
    end
  end

  resources :maps do
    resources :location_pins
    resources :locations do
      collection do
        get 'invite_page'
        get 'upload_page'
        post 'import'
      end
    end

    get 'style_editor'
    post 'style_img'

    member do
      post 'assign_manager_role'
      post 'assign_other_role'
    end
  end

  resources :locations do
    resources :photos
  end

  resources :photos

  resources :factories  do
    collection do
      get 'demo1'
      get 'demo2'
    end
  end

end

app/models/map.rb
class Map < ActiveRecord::Base
  resourcify  #rolify setting
  has_many :locations, dependent: :destroy
  has_many :location_pins, dependent: :destroy
  accepts_nested_attributes_for :location_pins
  belongs_to :user
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController

  before_action :login_required, :only => [:new, :create, :update, :destroy]
  before_action :set_maps
  authorize_resource #cancan's setting

  def index
  end

  def new
    @map = Map.new
  end

  def edit
    @map = Map.find(params[:id])
  end

  def show

    @map = params[:id].present? ? Map.find(params[:id]) : Map.find_by_kind!(request.subdomain)
    @style = @map.style.to_json
  
    if @map.kind == "activity"
      #GetLocationsWorker.perform_async
      render :show_activity
    elsif @map.kind == "google"
      render :show_google
    elsif @map.kind == "sheethub"
      @data_url = params[:data_url]
      render :show_sheethub
    elsif @map.kind == "news"
      #GetNewsWorker.perform_async
      render :show_news
    end
  end

  def create
    @map = current_user.maps.build(map_params)
    if @map.save
      current_user.add_role :admin,@map

      redirect_to map_path(@map)
    else
      render :new
    end
  end

  def update
    @map = Map.find(params[:id])
    # binding.pry
    if @map.update(map_params)
      redirect_to map_path(@map)
    else
      render :edit
    end
  end

  def destroy
    @map = Map.find(params[:id])
    @map.destroy
    redirect_to maps_path, notice: "成功刪除了地圖"
  end


  def style_editor
    @map = Map.find(params[:map_id])
    @style = @map.style.to_json
  end

  def style_img
    # binding.pry
    res = {}
    # file = params[:se_img]
    # url = params[:se_img_url]
    file = params[:_im_upload]
    ac = params[:_im_action]
    base_path = File.expand_path(Rails.public_path)
    url_path = "uploads/style_image/map_#{params[:map_id]}"
    if file and ac == 'create'
      # new file
      file_path = FileUtils.mkdir_p("#{base_path}/#{url_path}")
      
      file_name = file.original_filename
      file_path = file_path[0]
      
      File.open("#{file_path}/#{file_name}", 'wb') { |f| f.write(file.read)}
      res['_im_res_url'] = "/#{url_path}/#{file_name}"
      res['success'] = true
    elsif ac == 'remove'
      # remove file
      # File.delete(path_to_file) if File.exist?(path_to_file)
      path = params[:_im_source]
      name = path.split(url_path)[1]
      if name
        # binding.pry
        File.delete("#{base_path}/#{url_path}#{name}")
        res['success'] = true
      end
    end
    respond_to do |format|
      format.json { render :json => res }
    end
  end

  def assign_manager_role
    assign_role("manager")
  end

  def assign_other_role
    assign_role("other")
  end

  private

  def map_params
    params.require(:map).permit(:title, :description, :private, :style, :location_pins_attributes => [:id, :pin])
  end

  def assign_role(role_name)
    @user = User.find_by(email: params[:email])

    if @user.present?
      @map = Map.find(params[:id])
      @user.add_role role_name, @map
      respond_to do |format|
        format.json { render json: "success", status: :created }
      end
    else
      respond_to do |format|
        format.json { render json: "no_user", status: :unprocessable_entity }
      end
    end
  end
end

app/helpers/maps_helper.rb
module MapsHelper

  def render_user_role_for_map(map)
    if current_user && is_existed_map(map)
      role = if Map.with_role(:manager, current_user).pluck(:id).include?(map.id)
        "你是地圖管理者"
      elsif Map.with_role(:invitee, current_user).pluck(:id).include?(map.id)
        "你是共同編輯者"
      else
        "你是一般使用者"
      end
    else
      "你是一般使用者"
    end
  end

  def render_map_title_for_map(map)

    if is_existed_map(map)
      "#{map.title}"
    else
      "地圖列表"
    end
  end

  def render_map_title_for_maplist(map)
    if map.private
      "#{map.title} (私房)"
    else
      "#{map.title} (公開)"
    end
  end

  def is_existed_map(map)
    map.present? && map.id?
  end
end

app/views/maps/_form.html.erb
<div id="over_map_form">

  <%= simple_form_for(@map) do |f| %>
  <%= render 'common/error_messages', object: f.object %>
  <div class="field">
    <%= f.input_field :title ,placeholder: '名稱',:required => true, maxlength: 25 %>
  </div>
  <br>
  <div class="field">
    <%= f.label "描述：" %>
    <%= f.input_field :description,:required => true,style: "display:none" %>
    <% content_for :trumbowyg_content do %>
    <% if !@map.description.nil? %>
    <%= sanitize @map.description %>
    <% end %>
    <% end %>
    <%= render template: "common/trumbowyg" %>
  </div>
  <% if can?(:create, @map) %>
  <div class="field">
    <%= f.input_field :private,inline_label: "設為私房地圖",as: :boolean %>
    <p>私房地圖：<ul><li>只有自已可以編輯</li><li>有連結的人才能觀看</li><li>不會出現在地圖列表內</li> </ul></p>
    <p>公開地圖：<ul><li>登入的使用者都可以編輯</li></ul></p>
  </div>
  <% end %>

  <%= f.simple_fields_for :location_pins do |p| %>
  <div class="field">
    <%= p.input :pin %>
  </div>
  <% end -%>

  <div class="actions">
    <%= f.submit '送出', :class => "btn btn-success" %>
  </div>
  <% end %>
  <% if current_user && current_user.id == 1 && request[:action] == "edit" %>
  <%= button_to '刪除', map_path(@map),class: "btn btn-danger pull-right", :method => :delete, data: { confirm: '你確定要刪除這個地圖嗎？' } %>
  <% end %>
</div>


<% content_for :javascripts do %>
<script type='text/javascript'>
(function(scope){
  $("input[type=submit]").on('click',function() {
    var form_id = $("form:eq(1)").attr("id");
    $("#map_description").val($("#trumbowyg").html());
    $( "#"+form_id ).submit();
  });
})(window);

</script>
<% end %>

app/views/maps/_map.html.erb
<style type="text/css">

#map {
  width: 100%;
  height: 100%;
}

</style>

<div id="map"></div>
<div id="content" style="display:none"></div>

app/views/maps/edit.html.erb
<% content_for :sidebar_content do %>


<h3>設定地圖</h3>

<% content_for :form_content do %>
<br>
<div class="field">
  <%= render template: "common/edit_location_pin_upload" %>
</div>
<% end %>
<%= render template: "maps/form" %>

<hr>
<h3>邀請好友共同管理地圖</h3>
<%= simple_form_for @map, url: invite_member_map_path, html: { method: :post} do |f| %>

<input type="text"  name="email" class="form-control" placeholder="your_friend@gmail.com" />
<br>
<%= f.button :submit, t("devise.invitations.new.submit_button"),class: "btn btn-success" %>
<% end %>

<% end %>
<%= render template: "common/sidebar_right" %>



<% content_for :javascripts do %>
<script type='text/javascript'>
  (function(){

    get_marker_and_pin_in_map(<%= @map.id %>,function(marker,map_id){
      marker.on('click',function(event){
        location.href = '/maps/'+map_id+'/locations/'+event.target.options.location_id;
      });
    });
  })();

</script>
<% end %>

app/views/maps/edit_js_str_page.html.erb
<% content_for :sidebar_content do %>
<h3>設定Javascript</h3>
<div id="over_map_form">

  <%= simple_form_for(@map) do |f| %>
  <%= render 'common/error_messages', object: f.object %>
  <div class="field">
    <%= f.input_field :js_str,:required => true, hidden: true %>
<div id="codeMirror"></div>
  </div>
  <br>
  <%= link_to 'Try to run it!', "#", id: "execute", :class => "btn btn-info" %>

  <%= f.submit 'Save', :class => "btn btn-success pull-right" %>
  <% end %>
</div>


<% end %>
<%= render template: "common/sidebar_right" %>



<% content_for :javascripts do %>
<script type='text/javascript'>

    get_marker_and_pin_in_map(<%= @map.id %>,function(marker,map_id){
      marker.on('click',function(event){
        location.href = '/maps/'+map_id+'/locations/'+event.target.options.location_id;
      });
    });
    var myTextArea = document.getElementById('map_js_str');
    var codeMirror = document.getElementById('codeMirror');
    var myCodeMirror = CodeMirror(function(elt) {
      codeMirror.parentNode.replaceChild(elt, codeMirror);
    }, {
      value: myTextArea.value,
      mode: {name: "javascript", json: true},
      lineNumbers: true});
    $('#execute').click(function(){
      var js = myCodeMirror.getValue();//http://codemirror.net/doc/manual.html#getValue
      var s = document.createElement('script');
      s.textContent = js;//inne
      document.body.appendChild(s);
    })


    $('[name=commit]').click(function(){
      $('#map_js_str').html(myCodeMirror.getValue());
    })



</script>
<% end %>

app/views/maps/index.html.erb
<% content_for :sidebar_content do %>

<%= render :partial => "common/sidebar_example" %>
<% end %>
<%= render template: "common/sidebar" %>

<% content_for :javascripts do %>

<script type='text/javascript'>
  (function(scope){
    var sidebar = L.control.sidebar('sidebar', {
      position: 'left'
    });

    map.addControl(sidebar);
    sidebar.show();

    var markers = new L.MarkerClusterGroup();

    get_marker_and_pin_in_map(<%= @random_map_id %>,function(marker,map_id){
      marker.on('click',function(event){
        var alatlng = event.latlng;
        $.ajax({
          url: '/maps/'+map_id+'/locations/' +event.target.options.location_id ,
          dataType:'script'
        }).success(function(data){
          sidebar.show();
        });
      });
    });

  })(window);

</script>
<% end %>

app/views/maps/new.html.erb
<% content_for :sidebar_content do %>

<h3>新增地圖</h3>
<%= render template: "maps/form" %>

<% end %>
<%= render template: "common/sidebar_right" %>


<% content_for :javascripts do %>


<script type='text/javascript'>
  (function(){

    <%= render :partial => "example/shifus_data" %>


  })();

</script>
<% end %>

app/views/maps/show.html.erb
<% content_for :sidebar_content do %>

<%= render "common/sidebar_index" %>
<% end %>
<%= render template: "common/sidebar" %>


<% content_for :javascripts do %>
<script type='text/javascript'>
  (function(scope){

    var sidebar = L.control.sidebar('sidebar', {
      position: 'left'
    });

    map.addControl(sidebar);
    sidebar.show();

    StyleDropper.drop(<%= sanitize @style %>);

    get_marker_and_pin_in_map(<%= @map.id %>,function(marker,map_id){
      marker.on('click',function(event){
        var alatlng = event.latlng;
        $.ajax({
          url: '/maps/'+map_id+'/locations/' +event.target.options.location_id ,
          dataType:'script'
        }).success(function(data){
            sidebar.show();
          });
      });
    });


  })(window);

</script>
<% end %>

app/views/maps/show_activity.html.erb
<% content_for :sidebar_content do %>
<%= render :partial => "common/sidebar_meetmap" %>

<% end %>
<%= render template: "common/sidebar" %>


<% content_for :javascripts do %>
<script type='text/javascript'>
  (function(scope){

    var sidebar = L.control.sidebar('sidebar', {
      position: 'left'
    });

    map.addControl(sidebar);
    sidebar.show();

    var markers = new L.MarkerClusterGroup();
    $.ajax({
      url: "/maps/<%= @map.id %>/locations",
      dataType: "json",
      success: function (data) {
        var keysArray = Object.keys(data);
        for (var i in keysArray){
        // var circle = L.circle([data[keysArray[i]][1], data[keysArray[i]][0]], 500, {
        //   color: 'red',
        //   fillColor: '#f03',
        //   fillOpacity: 0.5
        // }).addTo(map);
        // circle.bindPopup(data[keysArray[i]][2]);
        if(!data[keysArray[i]]["lat"] || !data[keysArray[i]]["start_at"]){
          continue;
        }
        var title = data[keysArray[i]]["title"];
        var location_id = data[keysArray[i]]["id"];
        var marker = L.marker([data[keysArray[i]]["lat"], data[keysArray[i]]["lng"]],{location_id:location_id, icon:otherIcon, title:title, start_at:data[keysArray[i]]["start_at"].replace('T', ' '), end_at:data[keysArray[i]]["end_at"]} );

        markers.addLayer(marker);
        map.fitBounds(markers.getBounds());
        var callback = function(event,location_id){
          var alatlng = event.latlng;
          $.ajax({
            url: '/maps/<%= @map.id %>/locations/' +location_id ,
            dataType:'script'
          }).success(function(data){
            // event.target.bindPopup($('#content').html());
            // event.target.openPopup();
            sidebar.show();
            console.log(data);
            map.panTo(alatlng);
            map.zoomIn(6);
          });
        };
        $('#event_list').prepend('<table class="table table-striped"><tr><td><a id="location_'+location_id+'" data-id='+location_id+'><h4>'+title+'<h4></a></td></tr></table>');

        $('#location_'+location_id).bind('click',function(event){
          callback(event,$(this).attr('data-id'));
        });

        // var text = "<h2>"+data[keysArray[i]]["title"]+"</h2>";
        // marker.bindPopup(text);

        marker.on('click',function(event){
          callback(event,event.target.options.location_id);
        });
      }

      //map.addLayer(marker);

      var sliderControl = L.control.sliderControl({layer: markers,position: 'bottomleft',range: true, timeAttribute: "start_at", alwaysShowDate: true, showAllOnStart: true });
      map.addControl(sliderControl);
      sliderControl.startSlider();
    }
  });


})(window);

</script>
<% end %>

app/views/maps/show_event.html.erb
<%= render :partial => "maps/map" %>
<% content_for :sidebar_content do %>
<%= render :partial => "common/sidebar_meetmap" %>

<% end %>
<%= render template: "common/sidebar" %>


<% content_for :javascripts do %>
<script type='text/javascript'>
  (function(scope){

    var sidebar = L.control.sidebar('sidebar', {
      position: 'left'
    });

    map.addControl(sidebar);
    sidebar.show();

    var markers = new L.MarkerClusterGroup();
    $.ajax({
      url: "/maps/<%= @map.id %>/locations",
      dataType: "json",
      success: function (data) {
        var keysArray = Object.keys(data);
        for (var i in keysArray){
        // var circle = L.circle([data[keysArray[i]][1], data[keysArray[i]][0]], 500, {
        //   color: 'red',
        //   fillColor: '#f03',
        //   fillOpacity: 0.5
        // }).addTo(map);
        // circle.bindPopup(data[keysArray[i]][2]);
        if(!data[keysArray[i]]["lat"] || !data[keysArray[i]]["start_at"]){
          continue;
        }
        var title = data[keysArray[i]]["title"];
        var location_id = data[keysArray[i]]["id"];
        var marker = L.marker([data[keysArray[i]]["lat"], data[keysArray[i]]["lng"]],{location_id:location_id, icon:otherIcon, title:title, start_at:data[keysArray[i]]["start_at"].replace('T', ' '), end_at:data[keysArray[i]]["end_at"]} );

        markers.addLayer(marker);
        var callback = function(event,location_id){
          var alatlng = event.latlng;
          $.ajax({
            url: '/maps/<%= @map.id %>/locations/' +location_id ,
            dataType:'script'
          }).success(function(data){
            // event.target.bindPopup($('#content').html());
            // event.target.openPopup();
            sidebar.show();
            console.log(data);
            map.panTo(alatlng);
            map.zoomIn(6);
          });
        };
        $('#event_list').append('<table class="table table-striped"><tr><td><a id="location_'+location_id+'" data-id='+location_id+'><h4>'+title+'<h4></a></td></tr></table>');

        $('#location_'+location_id).bind('click',function(event){
          callback(event,$(this).attr('data-id'));
        });

        // var text = "<h2>"+data[keysArray[i]]["title"]+"</h2>";
        // marker.bindPopup(text);

        marker.on('click',function(event){
          callback(event,event.target.options.location_id);
        });
      }

      //map.addLayer(marker);

      var sliderControl = L.control.sliderControl({layer: markers,position: 'bottomleft',range: true, timeAttribute: "start_at", alwaysShowDate: true, showAllOnStart: true });
      map.addControl(sliderControl);
      sliderControl.startSlider();
    }
  });


})(window);

</script>
<% end %>

app/views/maps/show_google.html.erb
<% content_for :sidebar_content do %>

<%= render "common/sidebar_index" %>
<% end %>
<%= render template: "common/sidebar" %>


<% content_for :javascripts do %>
<script type="text/javascript" src="https://www.google.com/jsapi"></script>
<script type='text/javascript'>
  (function(scope){

    var sidebar = L.control.sidebar('sidebar', {
      position: 'left'
    });

    map.addControl(sidebar);
    sidebar.show();

    var markers = new L.MarkerClusterGroup();
    google.load('visualization', '1.0');

    // Set a callback to run when the Google Visualization API is loaded.
    google.setOnLoadCallback(drawChart);

    // Callback that creates and populates a data table,
    // instantiates the pie chart, passes in the data and
    // draws it.
    function drawChart() {

      var URL = 'http://spreadsheets.google.com/tq?key=1h04BlU1H3deYk3XXqiXMsx17nhQD4VvZ7CcCVOxBfkY';
      google.load('visualization', '1');
      var query = new google.visualization.Query(URL);
      // 使用 query language 查詢資料
      query.setQuery('select A,B,C,D,E,F');
      query.send(function(resp){
        if (!resp.isError()) {
          var dataTable = resp.getDataTable();
          var jsonData = JSON.parse(dataTable.toJSON());
          var locations_data = _.map(jsonData.rows, function(data){
            var locations_data2 = _.map(data, function(data2){
              return {name: data2[0] ? data2[0].v : '',
              address: data2[1] ? data2[1].v : '',
              contact: data2[2] ? data2[2].v : '',
              description: data2[3] ? data2[3].v : '',
              open_time: data2[4] ? data2[4].v : '',
              item: data2[5] ? data2[5].v : ''}
            });
            return locations_data2[0];
          })
        }
        var title_chinese = locations_data[0];
        var getLocation = function (location) {
          return function(){
            if (!location || location["address"].length == 0 || location["address"] === '地址'){
              return;
            }

            $.ajax({
              url:'http://maps.googleapis.com/maps/api/geocode/json',
              data:{
                address:location["address"],
                region: 'tw'
              },
              dataType:'json',
              success: function (data) {
                var lat_lng = (data["results"]) ? data["results"][0]["geometry"]["location"] : '' ;
                var title = location["name"];
                var marker = L.marker([lat_lng["lat"], lat_lng["lng"]],{icon:otherIcon,title:title} );

                markers.addLayer(marker);
                marker.on('click',function(event){
                  $('#sidebar').html(transfer_to_html(title_chinese,location));
                  sidebar.show();
                });
                map.addLayer(markers);
              }
            });
          }};
          for (var i=0; i < locations_data.length; i++){
            setTimeout(getLocation(locations_data[i]), 110*i);
          }
          setTimeout(
            function(){map.fitBounds(markers.getBounds());}
            ,locations_data.length*110
            );
        });
};


})(window);

function transfer_to_html(title, object){
  var name = object["name"];
  var address = object["address"];
  var contact = object["contact"];
  var description = object["description"];
  var open_time = object["open_time"];
  var item = object["item"];

  var con = function(tagname, content){
    return '<' + tagname + '>' + content + '</' + tagname + '>';
  };

  var result = '';
  if (object["name"]){
    result += con('h1', title['name'])+
    con('h2', object["name"]);
  }
  if (object["address"]){
    result += con('h2', title['address'])+
    con('pre', object["address"]);
  }
  if (object["contact"]){
    result += con('h2', title['contact'])+
    con('pre', object["contact"]);
  }
  if (object["description"]){
    result += con('h2', title['description'])+
    con('pre', object["description"]);
  }
  if (object["open_time"]){
    result += con('h2', title['open_time'])+
    con('pre', object["open_time"]);
  }
  if (object["item"]){
    result += con('h2', title['item'])+
    con('pre', object["item"]);
  }

  return result;

}

</script>

<% end %>

app/views/maps/show_kind.html.erb
<% content_for :sidebar_content do %>

<%= render "common/sidebar_index" %>
<% end %>
<%= render template: "common/sidebar" %>
<code id="myCodeMirror" style="display:none"><%= @js_str %></code>

<% content_for :javascripts do %>
<script type='text/javascript'>
  (function(scope){

    var sidebar = L.control.sidebar('sidebar', {
      position: 'left'
    });

    map.addControl(sidebar);
    sidebar.show();

    var js = $('#myCodeMirror').text();
    var s = document.createElement('script');
    s.textContent = js;//inne
    document.body.appendChild(s);
  })(window);

</script>
<% end %>

app/views/maps/style_editor.html.erb
<% content_for :sidebar_content do %>


<% end %>
<%= render template: "common/sidebar" %>

<%= render template: "common/sidebar_right" %>

<% content_for :javascripts do %>

<script type='text/javascript'>
(function(scope){
  var sidebar = L.control.sidebar('sidebar', {
    position: 'left'
  });

  map.addControl(sidebar);
  sidebar.show();

  StyleDropper.drop(<%= sanitize @style %>);

  var markers = new L.MarkerClusterGroup();

})(window);

var hightlighter;
var editor;

$(window).load(function(){

  // Add 'rh' attribute to element for highlight
  hightlighter = new RegionHighlighter(document.body, { querySelector: "[se-id]" });

  editor = new StyleEditor({
    renderTo: document.getElementById('float-editor'),
    imageUploadOptions:{
      url:{
        create: '<%= map_style_img_path(@map) %>',
        remove: '<%= map_style_img_path(@map) %>'  
      },
      lazyUpload: true,
      uploadText: 'Choose...',
      uploadParams:{ "authenticity_token" : $('[name=csrf-token]').attr('content') },
      removeParams:{ "authenticity_token" : $('[name=csrf-token]').attr('content') },
      filenameGenFn: function(name){
        return [$(this._el).parents("[se-map-id]").attr('se-map-id'), name].join('_');
      },
    },
    submitText: 'Save',
    submitClick: function(event, el){
      // $.ajax({
      //   type: "post",
      //   url: url,
      //   data: {
      //     authenticity_token: $('[name=csrf-token]').attr('content'),
      //     _method: 'patch',
      //     map:{
      //       style: JSON.stringify(StyleDropper.suck("se-id"))
      //     }
      //   },
      //   success: function(data, status, xhr){
      //   },
      //   dataType: 'json'
      // });
      editor.uploadFiles(function(){
        $('#style_string').text(JSON.stringify(StyleDropper.suck("se-id")));
        document.getElementById('style_submit_id').click();
      });
    }
  });

  hightlighter.onclick(function(o, e){
    var id = $(this).attr("se-id");
    if(id){
      editor.setActive(id);
    }
  });

  // editor.syncByElement();
  editor.setActive(0);
  editor.show();


  // hightlighter.onclick(function(o, e){ alert("shit"); });
  
  // hightlighter.addRegion(".leaflet-sidebar #sidebar", {
  //   click: function(o, e){ alert("sidebar left"); }
  // });
  // hightlighter.addRegion(".leaflet-control-container .left .close", {
  //   click: function(o, e){ alert("close left"); }
  // });
  // hightlighter.addRegion(".leaflet-sidebar #sidebar_right", {
  //   click:function(o, e){ alert("sidebar right"); }
  // });
  // hightlighter.addRegion(".leaflet-control-container .right .close", {
  //   click: function(o, e){ alert("close right"); }
  // });
  
  // // select the target node
  // var target = document.querySelector('#sidebar');
   
  // // create an observer instance
  // var observer = new MutationObserver(function(mutations) {
  //   mutations.forEach(function(mutation) {
  //     console.log(mutation.type);
  //   });    
  // });
   
  // // configuration of the observer:
  // var config = { attributes: true, childList: true, characterData: true, attributeOldValue: true };
   
  // // pass in the target node, as well as the observer options
  // observer.observe(target, config);

  // var up = document.getElementById('bimgUpload');
  // up.addEventListener('change', function(e){
  //   var self = this;
  //   if(self._isUploading !== true){
  //     self._isUploading = true;
  //     if(self.files.length){
  //       // create
  //       var f = new FormData();
  //       var fileBlob = self.files[0];
  //       f.append(self.name, fileBlob, 'id_bk_img');
  //       f.append("authenticity_token", $('[name=csrf-token]').attr('content'));
  //       f.append("img_url", '');
  //       $.ajax({
  //         type: "POST",
  //         url: '<%= map_style_img_path(@map) %>',
  //         cache: false,
  //         contentType: false,
  //         processData: false,
  //         data: f,
  //         success: function(o){
  //           self._isUploading = false;
  //           alert(JSON.stringify(o));
  //         },
  //         error:function(o, title, content){
  //           self._isUploading = false;

  //         }
  //       });
  //     }else{
  //       // delete

  //     }
  //   }
  // });
});

</script>
<% end %>
<div id="float-editor">
  <!-- <input id="bimgUpload" type="file" name="se_img" accept="image/*"/> -->
  <%= simple_form_for @map, :html => { :style => 'display:none' } do |f| %>
  <%= f.input_field :style, as: :text, id: 'style_string' %>
  <%= f.submit '送出', id:'style_submit_id' %>
  <% end %>
</div>