config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  get '', to: 'maps#show', constraints: lambda { |r| r.subdomain.present? && r.subdomain != 'www' }
  root 'maps#index'

  require 'sidekiq/web'
  authenticate :user, lambda { |u| u.id == 1 } do
    mount Sidekiq::Web => '/sidekiq'
  end

  arrayMap = (1..6).map { |x| %Q(get 'index#{x}'\n)}
  arrayMapReduce = arrayMap.reduce { |x,y| x+y }

  resources :welcome do
    collection do
      get 'demo'
      get 'search_location'
      eval(arrayMapReduce)
    end
  end

  resources :maps do
    resources :location_pins
    resources :locations do
      collection do
        get 'invite_page'
        get 'upload_page'
        post 'import'
      end
    end

    get 'style_editor'
    post 'style_img'

    member do
      post 'assign_manager_role'
      post 'assign_other_role'
    end
  end

  resources :locations do
    resources :photos
  end

  resources :photos

  resources :factories  do
    collection do
      get 'demo1'
      get 'demo2'
    end
  end

end

app/views/common/_facebook_js.erb
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) {return;}
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/zh_TW/all.js#xfbml=1&appId=<%= Setting.facebook_app_id %>";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

app/views/common/_footer.html.erb
<hr>

<footer>
  <p>&copy;2014 <%= Setting.app_name %> All rights reserved.</p>
</footer>

app/views/common/_google_analytics.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', '<%= Setting.google_analytics_key %>', 'auto');
  ga('send', 'pageview');

</script>

app/views/common/_not_logined.js.erb
if (confirm("Please login first, proceed?") )
{
	window.location = "/users/sign_in";
}

app/views/common/_search_form.html.erb
<div class="navbar-form navbar-left" role="form">
  <input type="text" id="search_location" name="q" class="form-control" value="<%= @query_string %>" placeholder="<%= @query_string ||   "搜尋地點" %>" />
</div>

<% content_for :javascripts do %>
<script type="text/javascript">
  (function(scope){
    if(!scope.myMarker){

      var location;

      if (typeof params !== "undefined" && params != ''){
        location = {lat: params.lat, lng: params.lng }
        map.setView(new L.LatLng(location.lat,
          location.lng), 16);
      }else{
        location = taiwanCenter
      }

      scope.myMarker = L.marker( location , {
        icon: myIcon,
        draggable: "true"
      }).addTo(map);

      setMarkerOnMapArea(myMarker,location,setLocationNumfunction);


      myMarker.on("dragend", function(e) {
        var position = e.target.getLatLng();
        setMarkerOnMapArea(e.target, position,setLocationNumfunction);
      });

      map.on("click", function(e) {
        setMarkerOnMapArea(myMarker, e.latlng,setLocationNumfunction);
      });

    }

    $('#search_location').keypress(function(e){
      code = (e.keyCode ? e.keyCode : e.which);
      if(code == 13){
        search_location($('#search_location').val());
      }
    });


    var search_location = function(queryString){
      $.ajax({
        url:'http://maps.googleapis.com/maps/api/geocode/json',
        data:{
          address:queryString,
          region: 'tw'
        },
        dataType:'json',
        success: (function(m,s){
          return function (data) {
            var lat_lng = (data["results"]) ? data["results"][0]["geometry"]["location"] : '' ;

            setMarkerOnMapArea(m,{lat: lat_lng["lat"], lng: lat_lng["lng"]},s);
            map.setZoom(15);

          }
        })(myMarker,setLocationNumfunction)
      });

    }

  })(window)
</script>
<% end %>

app/views/common/_sidebar.html.erb
<% content_for :stylesheets do %>

<%= stylesheet_link_tag "leaflet-sidebar/src/L.Control.Sidebar.css" %>


<% end %>
<div id="sidebar">
    <h1>leaflet-sidebar</h1>
<div id="trumbowyg">
    <p>A responsive sidebar plugin for for <a href="http://leafletjs.com/">Leaflet</a>, a JS library for interactive maps.</p>

    <p><b>Click on the marker to show the sidebar again when you've closed it.</b></p>

    <p>Other examples:</p>

    <ul>
        <li><a href="listing-markers.html">listing-markers example</a></li>
        <li><a href="two-sidebars.html">two-sidebars example</a></li>
    </ul>

    <p class="lorem">Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.</p>

    <p class="lorem">Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.</p>

    <p class="lorem">Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.</p>

    <p class="lorem">Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.</p>
    </div>
</div>

app/views/common/_sidebar_example.html.erb
<h1><%= Setting.app_name %></h1>
<div id="trumbowyg">
    <p><b>隨手拍，隨手紀錄。</b></p>
    <h2>創造屬於自已的地圖</h2>

    <ul>
        <%= link_to "以Factbook登入", "/users/auth/facebook",class: "btn btn-info" %>
    </ul>

    <h3 class="lorem">參加附近有趣的活動<h3>
    <img src="http://images.abic.com.tw/upload/eda/ida14.jpg" width="100%">
    <h3 class="lorem">分享家鄉的風景</h3>
    <img src="http://attach.bbs.miui.com/album/201411/10/123812ajs4b5kttldtubxb.jpg" width="100%">
    <h3 class="lorem">和朋友討論旅遊去處</h3>
    <img src="http://images2.sina.com/travel/news/spot/2010-01-11/U118P210T2D4627F11DT20100111003150.jpg" width="100%">
    <h3 class="lorem">規畫心目中的建築藍圖</h3>
    <img src="http://www.mottimes.com/image/news/7220130729181314.jpg" width="100%">
</div>

app/views/common/_sidebar_index.html.erb
<h1><%= @map.title %></h1>
<div id="trumbowyg">
  <%= sanitize @map.description %>
  <div id="event_list"></div>
</div>
<% if @map.user.present? %>
建立者：<%= @map.user.name %>
<% end %>

app/views/common/_sidebar_meetmap.html.erb
<h1><%= @map.title %><h1>
<div id="trumbowyg">
    <%= sanitize @map.description %>

    <div id="event_list"></div>
</div>

app/views/common/_user_nav.html.erb
<ul class="nav navbar-nav navbar-right">



  <li class="dropdown">
    <% if current_user %>

    <%= link_to "#" , :class => "dropdown-toggle", :data => { :toggle => "dropdown" } do %>
    <%= current_user.name %>
    <% end %>

    <ul class="dropdown-menu">

      <%#= link_to("設定","/users/edit" ) %>
      <li><%= link_to(render_user_role_for_map(@map),"#") %></li>
      <li><%= link_to("登出",destroy_user_session_path, :method => :delete ) %></li>
    </ul>

    <% else %>

    <li> <%= link_to( "註冊" ,new_user_registration_path) %> </li>
    <li> <%= link_to( "登入", new_user_session_path )  %> </li>
    <li> <%= link_to( "FACEBOOK登入", "/users/auth/facebook" )  %> </li>

    <% end %>
  </li>

</ul>

<% content_for :javascripts do %>
<% end %>

app/views/common/edit_image_upload.html.erb
<div id="over_map_form">

  <%= simple_form_for([@map,@location]) do |f| %>
  <%= render 'common/error_messages', object: f.object %>
  <div class="field">
    <%= f.input_field :title ,placeholder: '標題',:required => true, maxlength: 25 %>
  </div>

  <label class="string optional control-label">上傳圖片：</label>
  <%= content_tag(:div, class: "dropzone dropzone-previews", id: "my-awesome-dropzone") do %>
  <% photos.each do |photo| %>
  <div class="dz-preview dz-image-preview">
    <div class="dz-details">
      <div class="dz-id"><%= photo[:id] %></div>
      <div class="dz-filename"><span data-dz-name><%= photo[:photo] %></span></div>
      <div class="dz-size" data-dz-size></div>
      <img data-dz-thumbnail src="<%= "#{@fullpath}#{photo.photo}" %>"/>
    </div>
    <div class="dz-progress"><span class="dz-upload" data-dz-uploadprogress></span></div>
    <div class="dz-success-mark"><span>✔</span></div>
    <div class="dz-error-mark"><span>✘</span></div>
    <div class="dz-error-message"><span data-dz-errormessage></span></div>
    <a class="dz-remove" href="javascript:undefined;" data-dz-remove="">Remove file</a>
  </div>
  <% end %>
  <% end %>

  <br>
  <div class="field">
    <%= f.label "描述：" %>
    <%= f.input_field :content,:required => true,style: "display:none" %>
    <% content_for :trumbowyg_content do %>
    <% if !@location.content.nil? %>
    <%= sanitize @location.content %>
    <% end %>
    <% end %>
    <%= render template: "common/trumbowyg" %>
  </div>
  <br>
  <div class="field">
    <%= f.label "選擇代表圖示：" %>
    <%= f.collection_radio_buttons :location_pin_id,  @map.location_pins.map {|x| [x.id,image_tag(x.pin.url)]}, :first, :last  %>
  </div>
  <br>
  <div class="field">
    <%= f.label "網址連結：" %>
    <%= f.input_field :link_url, size: 48 %>
  </div>
  <div class="field">
    <%= f.label "經緯度：" %>
    <%= f.input_field :lat,readonly: true, maxlength: 20  %>
    <%= f.input_field :lng,readonly: true, maxlength: 20  %>
  </div>
  <br>
  <div class="actions">
    <%= f.submit "送出" %>
  </div>
  <% end %>
</div>

<% content_for :javascripts do %>
<%= javascript_include_tag "dropzone/dropzone.min.js" %>

<script type='text/javascript'>

  (function(scope){

    $('.dz-remove').on('click',function(){
      var id = this.parentNode.getElementsByClassName('dz-id')[0].innerText
      deleteFile(id);
      var mypreview = this.parentNode;
      console.log(mypreview);
      this.parentNode.parentNode.removeChild(mypreview);
    });

    var deleteFile = function(file_id){
      $.ajax({
        type: 'delete',
        url: '<%= location_photos_path(@location) %>/'+file_id,
        dataType: 'json'
      });
    }

    Dropzone.options.myAwesomeDropzone = {
      url: '<%= location_photos_path(@location) %>',
      paramName: "photo",
      previewsContainer: ".dropzone-previews",
      acceptedFiles: "image/*",
      uploadMultiple: false,
      parallelUploads: 100,
      maxFiles: 100,
      maxFilesize: 3,
      addRemoveLinks: true,
      removedfile: function(file) {
        var _ref;
        return (_ref = file.previewElement) != null ? _ref.parentNode.removeChild(file.previewElement) : void 0;
      },
      init: function() {
        var myDropzone = this;


        this.on("sending", function(file, xhr, formData) {
          formData.append("authenticity_token", $('[name=csrf-token]').attr('content'));
          formData.append("photoable_type", 'Location');
          formData.append("photoable_id", <%= @location.id %>);

      // Gets triggered when the form is actually being sent.
      // Hide the success button or the complete form.
    });
        this.on("successmultiple", function(files, response) {
      // Gets triggered when the files have successfully been sent.
      // Redirect user or notify of success.
    });
        this.on("errormultiple", function(files, response) {
      // Gets triggered when there was an error sending the files.
      // Maybe show form again, and notify user of error
    });
      }

    };
    $("input[type=submit]").on('click',function(){
      $("#location_content").val($("#trumbowyg").html());
    });
  })(window);
</script>
<% end %>

app/views/common/edit_location_pin_upload.html.erb
  <label class="string optional control-label">上傳ICON：</label>
  <%= content_tag(:div, class: "dropzone dropzone-previews", id: "my-awesome-dropzone") do %>
  <% @map.location_pins.each do |photo| %>
  <div class="dz-preview dz-image-preview">
    <div class="dz-details">
      <div class="dz-id"><%= photo[:id] %></div>
      <div class="dz-filename"><span data-dz-name><%= photo[:pin] %></span></div>
      <div class="dz-size" data-dz-size></div>
      <img data-dz-thumbnail src="<%= "#{@fullpath}#{photo.pin}" %>"/>
    </div>
    <div class="dz-progress"><span class="dz-upload" data-dz-uploadprogress></span></div>
    <div class="dz-success-mark"><span>✔</span></div>
    <div class="dz-error-mark"><span>✘</span></div>
    <div class="dz-error-message"><span data-dz-errormessage></span></div>
    <a class="dz-remove" href="javascript:undefined;" data-dz-remove="">Remove file</a>
  </div>
  <% end %>
  <% end %>


<% content_for :javascripts do %>
<%= javascript_include_tag "dropzone/dropzone.min.js" %>

<script type='text/javascript'>

  (function(scope){

    $('.dz-remove').on('click',function(){
      var id = this.parentNode.getElementsByClassName('dz-id')[0].innerText
      deleteFile(id);
      var mypreview = this.parentNode;
      console.log(mypreview);
      this.parentNode.parentNode.removeChild(mypreview);
    });

    var deleteFile = function(file_id){
      $.ajax({
        type: 'delete',
        url: '<%= map_location_pins_path(@map) %>/'+file_id,
        dataType: 'json'
      });
    }

    Dropzone.options.myAwesomeDropzone = {
      url: '<%= map_location_pins_path(@map) %>',
      paramName: "photo",
      previewsContainer: ".dropzone-previews",
      acceptedFiles: "image/*",
      uploadMultiple: false,
      parallelUploads: 100,
      maxFiles: 100,
      maxFilesize: 3,
      addRemoveLinks: true,
      removedfile: function(file) {
        var _ref;
        return (_ref = file.previewElement) != null ? _ref.parentNode.removeChild(file.previewElement) : void 0;
      },
      init: function() {
        var myDropzone = this;


        this.on("sending", function(file, xhr, formData) {
          formData.append("authenticity_token", $('[name=csrf-token]').attr('content'));


      // Gets triggered when the form is actually being sent.
      // Hide the success button or the complete form.
    });
        this.on("successmultiple", function(files, response) {
      // Gets triggered when the files have successfully been sent.
      // Redirect user or notify of success.
    });
        this.on("errormultiple", function(files, response) {
      // Gets triggered when there was an error sending the files.
      // Maybe show form again, and notify user of error
    });
      }

    };
    $("input[type=submit]").on('click',function(){
      $("#location_content").val($("#trumbowyg").html());
    });
  })(window);
</script>
<% end %>

app/views/common/new_image_upload.html.erb
<div id="over_map_form">

  <%= simple_form_for([@map,@location]) do |f| %>
  <%= render 'common/error_messages', object: f.object %>
  <div class="field">
    <%= f.input_field :title ,placeholder: '標題',:required => true, maxlength: 25 %>
  </div>
  <br>
  <div class="field">
    <label class="string optional control-label">上傳圖片：</label>
    <%= content_tag(:div, class: "dropzone dropzone-previews", id: "my-awesome-dropzone") do %>

    <% end %>

  </div>
  <br>
  <div class="field">
    <%= f.label "描述：" %>
    <%= f.input_field :content,:required => true,style: "display:none" %>
    <% content_for :trumbowyg_content do %>
    <% if !@location.content.nil? %>
    <%= sanitize @location.content %>
    <% end %>
    <% end %>
    <%= render template: "common/trumbowyg" %>
  </div>
  <br>
  <div class="field">
    <%= f.label "圖示：" %>
    <%= f.collection_radio_buttons :location_pin_id,  @map.location_pins.map {|x| [x.id,image_tag(x.pin.url)]}, :first, :last  %>
  </div>
  <br>
  <div class="field">
    <%= f.label "網址連結：" %>
    <%= f.input_field :link_url, size: 48 %>
  </div>
  <div class="field">
    <%= f.label "經緯度：" %>
    <%= f.input_field :lat,readonly: true, maxlength: 20  %>
    <%= f.input_field :lng,readonly: true, maxlength: 20  %>
  </div>
  <br>
  <div class="actions">
    <input type="button" name="commit" id="sendButton" value="送出" />
  </div>
  <% end %>
</div>

<% content_for :javascripts do %>
<%= javascript_include_tag "dropzone" %>
<script type='text/javascript'>

//window.originFileIds = [];
window.uploadFileList = [];
window.addedParams = {};

var doSubmitProcess = function(url, formId) {
  var file, formData, handleError, headerName, headerValue, headers, i, input, inputName, inputType, key, option, progressObj, response, updateProgress, value, xhr, _i, _j, _k, _l, _len, _len1, _len2, _len3, _m, _ref, _ref1, _ref2, _ref3, _ref4, _ref5, formEl;
  xhr = new XMLHttpRequest();

  xhr.open("POST", url, true);
  xhr.withCredentials = false;
  response = null;


  xhr.onreadystatechange=function(){
   if (xhr.readyState==4 && xhr.status==200){
     window.document.write(xhr.response);
   }

 }

 headers = {
    // "Accept": "application/json",
    //"Accept": "multipart/form-data",
    //"Accept": "application/x-www-form-urlencoded",
    "Cache-Control": "no-cache",
    "X-Requested-With": "XMLHttpRequest"
  };

  for (headerName in headers) {
    headerValue = headers[headerName];
    xhr.setRequestHeader(headerName, headerValue);
  }
  formData = new FormData();

  formEl = document.getElementById(formId);
  _ref2 = formEl.querySelectorAll("input, textarea, select, button");
  for (_k = 0, _len2 = _ref2.length; _k < _len2; _k++) {
    input = _ref2[_k];
    inputName = input.getAttribute("name");
    inputType = input.getAttribute("type");
    if (input.tagName === "SELECT" && input.hasAttribute("multiple")) {
      _ref3 = input.options;
      for (_l = 0, _len3 = _ref3.length; _l < _len3; _l++) {
        option = _ref3[_l];
        if (option.selected) {
          formData.append(inputName, option.value);
        }
      }
    } else if (!inputType || ((_ref4 = inputType.toLowerCase()) !== "checkbox" && _ref4 !== "radio") || input.checked) {
      formData.append(inputName, input.value);
    }
  }

  for(var i = 0, len = uploadFileList.length; i < len; i++){
    formData.append("photo["+i+"]", uploadFileList[i], uploadFileList[i].name);
  }


  for(var k in addedParams){
    formData.append(k, addedParams[k]);
  }
  return xhr.send(formData);
};


(function(scope){
 var foundForm = $(".dropzone").parents("form")[0];


 Dropzone.options.myAwesomeDropzone = {

  url: foundForm.action,
  paramName: "photo",
  previewsContainer: ".dropzone-previews",
  acceptedFiles: "image/*",
  uploadMultiple: false,
  parallelUploads: 100,
  maxFiles: 100,
  maxFilesize: 3,
  autoProcessQueue: false,
  addRemoveLinks: true,
  removedfile: function(file) {

    _.remove(uploadFileList,function(uploadFile){
      return file.name === uploadFile.name
    })

    var _ref;
    return (_ref = file.previewElement) != null ? _ref.parentNode.removeChild(file.previewElement) : void 0;
  },
  init: function() {
    var myDropzone = this;


    addedParams["authenticity_token"] = $('[name=csrf-token]').attr('content');


    this.on("successmultiple", function(files, response) {

    });
    this.on("errormultiple", function(files, response) {

    });
    this.on("addedfile",function(file){
      uploadFileList.push(file);
    });


  }

};

$("#sendButton").on('click',function(e) {

  $("#location_content").val($("#trumbowyg").html());
  doSubmitProcess(foundForm.action, $("form:eq(0)").attr("id"));

});
})(window);

</script>
<% end %>

app/views/common/sidebar.html.erb
<div id="sidebar" se-id="location_content" se-attr="background-color background-image">
  <%= notice_message %>
  <%= yield :sidebar_content %>
</div>