config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  get '', to: 'maps#show', constraints: lambda { |r| r.subdomain.present? && r.subdomain != 'www' }
  root 'maps#index'

  require 'sidekiq/web'
  authenticate :user, lambda { |u| u.id == 1 } do
    mount Sidekiq::Web => '/sidekiq'
  end

  arrayMap = (1..6).map { |x| %Q(get 'index#{x}'\n)}
  arrayMapReduce = arrayMap.reduce { |x,y| x+y }

  resources :welcome do
    collection do
      get 'demo'
      get 'search_location'
      eval(arrayMapReduce)
    end
  end

  resources :maps do
    resources :location_pins
    resources :locations do
      collection do
        get 'invite_page'
        get 'upload_page'
        post 'import'
      end
    end

    get 'style_editor'
    post 'style_img'

    member do
      post 'assign_manager_role'
      post 'assign_other_role'
    end
  end

  resources :locations do
    resources :photos
  end

  resources :photos

  resources :factories  do
    collection do
      get 'demo1'
      get 'demo2'
    end
  end

end

app/models/location.rb
require 'csv'
require 'iconv'
class Location < ActiveRecord::Base
  belongs_to :map
  belongs_to :user
  belongs_to :location_pin
  has_many :photos, as: :photoable, dependent: :destroy
  accepts_nested_attributes_for :photos

  validates :title, :presence => {:message => '是必填欄位'}

  scope :activity, -> {where("start_at > ?",Time.now).order('start_at desc')}
  scope :news, -> {where("start_at > ?", 6.hour.ago ).order('start_at asc')}

  before_save :check_if_url_exist_http_or_add_prefix

  def check_if_url_exist_http_or_add_prefix
    if (!self.link_url.blank?)
      temp_url = self.link_url
      added_http_url = (temp_url.start_with?("http://","https://")) ? temp_url : "http://"+temp_url

      self.link_url = url_is_valid?(added_http_url) ? added_http_url : ""
    end
  end

  def url_is_valid?(url)
    uri = URI.parse(url)
    uri.kind_of?(URI::HTTP)
  rescue URI::InvalidURIError
    false
  end

  @allowed_attributes = [ "title","content","address","lng","lat","link_url","outer_photo_url"]

  def self.import(map_id,file)
    spreadsheet = open_spreadsheet(file)
    header = spreadsheet.row(1)
    (2..spreadsheet.last_row).each do |i|
      row = Hash[[header, spreadsheet.row(i)].transpose]
      product = find_by_id(row["id"]) || new(map_id: map_id)
      product.attributes = row.to_hash.slice(*@allowed_attributes)
      product.save!
    end
  end

  def self.open_spreadsheet(file)
    case File.extname(file.original_filename)
    when ".csv" then Csv.new(file.path, nil, :ignore)
    when ".xls" then Roo::Excel.new(file.path, nil, :ignore)
    when ".xlsx" then Roo::Excelx.new(file.path, nil, :ignore)
    else raise "Unknown file type: #{file.original_filename}"
    end
  end

  def self.to_csv(options = {})
    CSV.generate(options) do |csv|
      csv << @allowed_attributes
      all.each do |location|
        csv << location.attributes.values_at(*@allowed_attributes)
      end
    end
  end

end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  skip_before_action :verify_authenticity_token

  before_action :login_required, :only => [:new,:create]
  before_action :set_maps
  authorize_resource #cancan's setting


  # GET /maps/1/locations.json
  def index
    @map = Map.find(params[:map_id])
    if @map.kind == "activity"
      @locations = @map.locations.activity
    elsif @map.kind == "news"
      @locations = @map.locations.news
    else
      @locations = @map.locations
    end
    respond_to do |format|
      format.json { render :json => @locations.as_json(:include => :location_pin)}
    end
  end

  # GET /maps/1/locations/1.js
  def show
    @map = Map.find(params[:map_id])
    @location = Location.find(params[:id])
    @photos = @location.photos.all

    respond_to do |format|
      format.html
      format.js
    end
  end

  def new
    @map = Map.find(params[:map_id])
    @location = @map.locations.new
    @location.lat = 23.974093
    @location.lng = 120.979903
    @location.photos.build
  end

  def edit
    @map = Map.find(params[:map_id])
    @location = Location.find(params[:id])
  end

  def create
    @map = Map.find(params[:map_id])
    @location = current_user.locations.build(location_params.merge(map_id: @map.id))
    if @location.save
      if !params[:photo].blank?
        photo_params.each.with_index.each do |photo|
          Photo.create!(photo: photo[1], photoable_type: "Location",photoable_id: @location.id)
        end
      end
      redirect_to map_location_path(@map,@location)
    else
      render :new
    end
  end

  def update
    @map = Map.find(params[:map_id])
    @location = Location.find(params[:id])
    if @location.update(location_params)

      redirect_to map_location_path(@map,@location)
    else
      render :edit
    end
  end

  def destroy
    @map = Map.find(params[:map_id])
    @location = Location.find(params[:id])

    @location.destroy

    redirect_to map_path(@map)
  end

  def invite_page
    @map = Map.find(params[:map_id])
    @locations = @map.locations

    @manager_users = User.with_role([:admin],@map) + User.with_role([:manager],@map)
  end

  def upload_page
    @map = Map.find(params[:map_id])
    @locations = @map.locations
    respond_to do |format|
      format.html
      format.csv { send_data @locations.to_csv }
      format.xls { send_data @locations.to_csv(col_sep: "\t") }
    end
  end

  def import
    @map = Map.find(params[:map_id])
    Location.import(params[:map_id],params[:file])
    redirect_to map_path(@map), notice: "位置已匯入。"
  end

  private
  def location_params
    params.require(:location).permit(:title,:content,:link_url,:lat,:lng,:location_pin_id)
  end

  def photo_params
    params.require(:photo)
  end

end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/views/locations/_window.html.erb
<header class="note-header">
  <h1 class="note-heading"><%= link_to @location.title , @location.link_url, target: '_blank'  %></h1>
</header>
 <hr>
<div class="note-contents">
  <div class="note-media">
    <div class="note-media-object">
      <figure>
        <% if !@photos.nil?  %>
        <% @photos.each do |photo| %>
        <%= image_tag(photo.photo.send("thumb").url, :class => "thumbnail") %>
        <% end %>
        <% end %>
        <% if @location.outer_photo_url.present?  %>
        <%= image_tag(@location.outer_photo_url, :class => "thumbnail",:style => "width:100%") %>
        <% end %>
      </figure>
    </div>
  </div>
  <div class="note-message">
    <h4><%= sanitize @location.content %></h4>
  </div>
  <hr>
  <h4><%= link_to '原始連結', @location.link_url, target: '_blank'  %></h4>
  <% if !@location.user.nil?  %>
  <h6 class="note-author">Steper: <%= @location.user.name %></h6>
  <% end %>
  <% if can?(:change_map, @map) && @map.kind.blank? %>
  <%= link_to "修改", edit_map_location_path(@map,@location), class: "btn btn-info"  %>
  <% end %>
</div>

app/views/locations/edit.html.erb
<% content_for :sidebar_content do %>

<h3>修改位置</h3>


<%= render template: "common/edit_image_upload",locals: {photos: @location.photos} %>

<br>
<%= button_to('刪除此地點', map_location_path(@map,@location), method: :delete , data: { confirm: '你確定要刪除嗎？' } , class:"btn btn-danger",style: "float:right") %>


<% end %>
<%= render template: "common/sidebar_right" %>




<% content_for :javascripts do %>
<script type='text/javascript'>
  (function(scope){

    scope.myMarker = L.marker({lat: <%= @location.lat %>, lng: <%= @location.lng %> }, {
      icon: myIcon,
      draggable: "true"
    }).addTo(map);

    map.setView(new L.LatLng(<%= @location.lat %>, <%= @location.lng %>), 16);


  })(window);

</script>
<% end %>

app/views/locations/form.html.erb
<div id="over_map_form">

  <%= simple_form_for([@map,@location]) do |f| %>
  <%= render 'common/error_messages', object: f.object %>
  <div class="field">
    <%= f.input_field :title ,placeholder: '標題',:required => true, maxlength: 25 %>
  </div>
  <%= yield :form_content %>
  <br>
  <div class="field">
    <%= f.label "描述：" %>
    <%= f.input_field :content,:required => true,style: "display:none" %>
    <% content_for :trumbowyg_content do %>
    <% if !@location.content.nil? %>
    <%= sanitize @location.content %>
    <% end %>
    <% end %>
    <%= render template: "common/trumbowyg" %>
  </div>
  <br>
  <div class="field">
    <%= f.label "網址連結：" %>
    <%= f.input_field :link_url, size: 48 %>
  </div>
  <div class="field">
    <%= f.label "經緯度：" %>
    <%= f.input_field :lat,readonly: true, maxlength: 20  %>
    <%= f.input_field :lng,readonly: true, maxlength: 20  %>
  </div>
  <br>
  <div class="actions">
    <%= f.submit "送出" %>
  </div>
  <% end %>
</div>

<% content_for :javascripts do %>
<script type='text/javascript'>
(function(scope){
  $("input[type=submit]").on('click',function() {
    var form_id = $("form:eq(0)").attr("id");
    $("#location_content").val($("#trumbowyg").html());
    $( "#"+form_id ).submit();
  });
})(window);

</script>
<% end %>

app/views/locations/invite_page.html.erb
<% content_for :sidebar_content do %>

<% if can?(:change_map, @map) %>
<h3>邀請</h3>
<input id="permission_email" maxlength="50" placeholder="輸入E-mail" size="50" type="text" value="">
<%= link_to "Go", "#" ,id:"permission_submit",class: "btn btn-default btn-xs" %>
<h3>設定權限</h3>


<table class="table table-striped">
  <thead>
    <tr>
      <th>管理者名單</th>
      <th>E-mail</th>
    </tr>
  </thead>
  <tbody>
    <% @manager_users.each_with_index do |u,index| %>
    <tr>
      <td><%= index+1 %></td>
      <td><%= u.email %></td>
    </tr>
    <% end %>

  </tbody>
</table>
<% end %>

<% end %>
<%= render template: "common/sidebar_right" %>



<% content_for :javascripts do %>
<script type='text/javascript'>
  (function(){

    get_marker_and_pin_in_map(<%= @map.id %>,function(marker,map_id){
      marker.on('click',function(event){
        location.href = '/maps/'+map_id+'/locations/'+event.target.options.location_id;
      });
    });


    $('#permission_submit').click(function(){
      $.ajax({
        url: '/maps/<%= @map.id %>/assign_manager_role',
        type:'post',
        dataType: "json",
        data: { email: $('#permission_email').val() },
        success: function(data) {
        //console.log(data);
        location.reload();
      },
      error: function(e){
        alert(e.statusText);
      }
    });

    });

  })();

</script>
<% end %>

app/views/locations/new.html.erb
<% content_for :sidebar_content do %>

<h3>新增位置</h3>

<%= render template: "common/new_image_upload" %>

<% end %>
<%= render template: "common/sidebar_right" %>


<% content_for :javascripts do %>
<script type='text/javascript'>
(function(scope){


var markers = new L.MarkerClusterGroup();
  $.ajax({
    url: "/maps/<%= @map.id %>/locations",
    dataType: "json",
    success: function (data) {
      var keysArray = Object.keys(data);
      for (var i=0; i<keysArray.length; i++){
        // var circle = L.circle([data[keysArray[i]][1], data[keysArray[i]][0]], 500, {
        //   color: 'red',
        //   fillColor: '#f03',
        //   fillOpacity: 0.5
        // }).addTo(map);
        // circle.bindPopup(data[keysArray[i]][2]);
        //console.log(data[keysArray[i]]);
        var marker = L.marker([data[keysArray[i]]["lat"], data[keysArray[i]]["lng"]],{icon:otherIcon} );
        markers.addLayer(marker);
        var text = "<h2>"+data[keysArray[i]]["title"]+"</h2>";
        marker.bindPopup(text);
      }
      map.addLayer(markers);
    }
  });


})(window);

</script>
<% end %>

app/views/locations/show.html.erb
<% content_for :sidebar_content do %>

<%= render :partial => "locations/window" %>

<% end %>
<%= render template: "common/sidebar" %>


<% content_for :javascripts do %>

<script type='text/javascript'>
  (function(scope){

    var sidebar = L.control.sidebar('sidebar', {
      position: 'left'
    });

    map.addControl(sidebar);

    sidebar.show();

    map.setView(new L.LatLng(<%= @location.lat %>, <%= @location.lng %>), 16);


    get_marker_and_pin_in_map(<%= @map.id %>,function(marker,map_id){
      marker.on('click',function(event){
        var alatlng = event.latlng;
        $.ajax({
          url: '/maps/'+map_id+'/locations/' +event.target.options.location_id ,
          dataType:'script'
        }).success(function(data){
          sidebar.show();
        });
      });
    });



  })(window);

</script>
<% end %>

app/views/locations/show.js.erb
$('#sidebar').html("<%= j(render :partial => '/locations/window') %>");

app/views/locations/upload_page.html.erb
<% content_for :sidebar_content do %>
<h2>匯入</h2>
<h4>格式需求:CSV、Excel</h4>
<ul>
  <li>標題:title </li>
  <li>內容:content </li>
  <li>連結:link_url </li>
  <li>地址:address </li>
  <li>經度:lng </li>
  <li>緯度:lat </li>
  <li>外部圖片網址:outer_photo_url</li>
</ul>

<%= form_tag(import_map_locations_path(@map), multipart: true) do %>
<%= file_field_tag 'file' %>
<br>
<%= submit_tag "匯入" %>
<% end %>
<h2>匯出</h2>
<%= link_to "CSV", upload_page_map_locations_path(@map,format: "csv") %> |
<%= link_to "Excel", upload_page_map_locations_path(@map,format: "xls") %>

<% end %>
<%= render template: "common/sidebar_right" %>


<% content_for :javascripts do %>
<script type='text/javascript'>
  (function(){

    get_marker_and_pin_in_map(<%= @map.id %>,function(marker,map_id){
      marker.on('click',function(event){
        location.href = '/maps/'+map_id+'/locations/'+event.target.options.location_id;
      });
    });


  })();

</script>
<% end %>